import { Request, Response } from 'express';
import https from 'https';
import pool from '../config/database.js';

// Rate limit Nominatim: 1 req/seg máximo
let lastNominatimCall = 0;
const waitRateLimit = async () => {
  const elapsed = Date.now() - lastNominatimCall;
  if (elapsed < 1200) await new Promise(r => setTimeout(r, 1200 - elapsed));
  lastNominatimCall = Date.now();
};

const httpsGet = (url: string): Promise<any[]> =>
  new Promise((resolve, reject) => {
    const parsed = new URL(url);
    https.get(
      { hostname: parsed.hostname, path: parsed.pathname + parsed.search, headers: { 'Accept-Language': 'es', 'User-Agent': 'OrbitM7-Logistics/1.9 (logistics@millasiete.com)' } },
      res => {
        let raw = '';
        res.on('data', c => (raw += c));
        res.on('end', () => { try { resolve(JSON.parse(raw)); } catch { resolve([]); } });
      }
    ).on('error', () => resolve([]));
  });

// Mapa base exhaustivo de municipios colombianos (bootstrap hasta que la DB aprenda)
const BASE_MAP: Record<string, string> = {
  // ANTIOQUIA
  'MEDELLIN':'ANTIOQUIA','ITAGUI':'ANTIOQUIA','ENVIGADO':'ANTIOQUIA','BELLO':'ANTIOQUIA','SABANETA':'ANTIOQUIA',
  'LA ESTRELLA':'ANTIOQUIA','COPACABANA':'ANTIOQUIA','GIRARDOTA':'ANTIOQUIA','CALDAS':'ANTIOQUIA','BARBOSA':'ANTIOQUIA',
  'RIONEGRO':'ANTIOQUIA','MARINILLA':'ANTIOQUIA','GUARNE':'ANTIOQUIA','CARMEN DE VIBORAL':'ANTIOQUIA',
  'CAUCASIA':'ANTIOQUIA','CAÑASGORDAS':'ANTIOQUIA','GOMEZ PLATA':'ANTIOQUIA','JARDIN':'ANTIOQUIA',
  'ARBOLETES':'ANTIOQUIA','SAN JUAN DE URABA':'ANTIOQUIA','SAN PEDRO':'ANTIOQUIA','AMAGA':'ANTIOQUIA',
  'LA CEJA':'ANTIOQUIA','SAN LUIS':'ANTIOQUIA','SONSON':'ANTIOQUIA','SANTA ROSA DE OSOS':'ANTIOQUIA',
  'APARTADO':'ANTIOQUIA','TURBO':'ANTIOQUIA','CAREPA':'ANTIOQUIA','CHIGORODO':'ANTIOQUIA',
  'MUTATA':'ANTIOQUIA','NECOCLÍ':'ANTIOQUIA','NECOCLI':'ANTIOQUIA','EL BAGRE':'ANTIOQUIA',
  'ZARAGOZA':'ANTIOQUIA','SEGOVIA':'ANTIOQUIA','REMEDIOS':'ANTIOQUIA','YOLOMBO':'ANTIOQUIA',
  'VEGACHI':'ANTIOQUIA','ANORI':'ANTIOQUIA','ANGOSTURA':'ANTIOQUIA','DON MATIAS':'ANTIOQUIA',
  'ENTRERRIOS':'ANTIOQUIA','ENTRERRÍOS':'ANTIOQUIA','BELMIRA':'ANTIOQUIA','SAN JOSE DE LA MONTAÑA':'ANTIOQUIA',
  'YARUMAL':'ANTIOQUIA','CAMPAMENTO':'ANTIOQUIA','VALDIVIA':'ANTIOQUIA','ITUANGO':'ANTIOQUIA',
  'TOLEDO':'ANTIOQUIA','DABEIBA':'ANTIOQUIA','URAMITA':'ANTIOQUIA','FRONTINO':'ANTIOQUIA',
  'ABRIAQUI':'ANTIOQUIA','URRAO':'ANTIOQUIA','BETULIA':'ANTIOQUIA','CAICEDO':'ANTIOQUIA',
  'CONCORDIA':'ANTIOQUIA','SALGAR':'ANTIOQUIA','ANDES':'ANTIOQUIA','BETANIA':'ANTIOQUIA',
  'HISPANIA':'ANTIOQUIA','TARAZA':'ANTIOQUIA','TARAZÁ':'ANTIOQUIA','CACERES':'ANTIOQUIA',
  'NECHÍ':'ANTIOQUIA','NECHI':'ANTIOQUIA','SAN PEDRO DE URABA':'ANTIOQUIA',
  'ABEJORRAL':'ANTIOQUIA','ARGELIA':'ANTIOQUIA','NARIÑO':'ANTIOQUIA',
  'LA UNION':'ANTIOQUIA','GRANADA':'ANTIOQUIA','COCORNA':'ANTIOQUIA','SAN CARLOS':'ANTIOQUIA',
  'SAN RAFAEL':'ANTIOQUIA','SAN ROQUE':'ANTIOQUIA','SAN VICENTE FERRER':'ANTIOQUIA',
  'ALEJANDRIA':'ANTIOQUIA','CONCEPCION':'ANTIOQUIA','CARACOLI':'ANTIOQUIA',
  'MACEO':'ANTIOQUIA','CISNEROS':'ANTIOQUIA','YALI':'ANTIOQUIA','AMALFI':'ANTIOQUIA',
  'FREDONIA':'ANTIOQUIA','VENECIA':'ANTIOQUIA','MONTEBELLO':'ANTIOQUIA','HELICONIA':'ANTIOQUIA',
  'ARMENIA ANTIOQUIA':'ANTIOQUIA','PUEBLORRICO':'ANTIOQUIA','CIUDAD BOLIVAR':'ANTIOQUIA',
  'LIBORINA':'ANTIOQUIA','SABANALARGA':'ANTIOQUIA','OLAYA':'ANTIOQUIA','PEQUE':'ANTIOQUIA',
  'GIRALDO':'ANTIOQUIA','SOPETRÁN':'ANTIOQUIA','SOPETRAN':'ANTIOQUIA',
  'BELLO ANTIOQUIA':'ANTIOQUIA','LA PINTADA':'ANTIOQUIA','VALPARAISO':'ANTIOQUIA',
  // VALLE DEL CAUCA
  'CALI':'VALLE DEL CAUCA','YUMBO':'VALLE DEL CAUCA','PALMIRA':'VALLE DEL CAUCA',
  'BUENAVENTURA':'VALLE DEL CAUCA','CARTAGO':'VALLE DEL CAUCA','GINEBRA':'VALLE DEL CAUCA',
  'LA CUMBRE':'VALLE DEL CAUCA','JAMUNDI':'VALLE DEL CAUCA','TULUA':'VALLE DEL CAUCA',
  'BUGA':'VALLE DEL CAUCA','GUADALAJARA DE BUGA':'VALLE DEL CAUCA','DAGUA':'VALLE DEL CAUCA',
  'VIJES':'VALLE DEL CAUCA','RESTREPO':'VALLE DEL CAUCA','CALIMA':'VALLE DEL CAUCA',
  'EL CERRITO':'VALLE DEL CAUCA','GUACARI':'VALLE DEL CAUCA','FLORIDA':'VALLE DEL CAUCA',
  'PRADERA':'VALLE DEL CAUCA','CANDELARIA':'VALLE DEL CAUCA','EL DOVIO':'VALLE DEL CAUCA',
  'VERSALLES':'VALLE DEL CAUCA','ARGELIA VALLE':'VALLE DEL CAUCA','EL AGUILA':'VALLE DEL CAUCA',
  'ANSERMANUEVO':'VALLE DEL CAUCA','ULLOA':'VALLE DEL CAUCA','ALCALA':'VALLE DEL CAUCA',
  'OBANDO':'VALLE DEL CAUCA','LA VICTORIA':'VALLE DEL CAUCA','ZARZAL':'VALLE DEL CAUCA',
  'ROLDANILLO':'VALLE DEL CAUCA','LA UNION VALLE':'VALLE DEL CAUCA','TORO':'VALLE DEL CAUCA',
  'BOLIVAR VALLE':'VALLE DEL CAUCA','RIOFRÍO':'VALLE DEL CAUCA','RIOFRIO':'VALLE DEL CAUCA',
  'TRUJILLO':'VALLE DEL CAUCA','BUGALAGRANDE':'VALLE DEL CAUCA','ANDALUCIA':'VALLE DEL CAUCA',
  'SEVILLA':'VALLE DEL CAUCA','CAICEDONIA':'VALLE DEL CAUCA',
  // CUNDINAMARCA / BOGOTA
  'BOGOTA':'CUNDINAMARCA','BOGOTÁ':'CUNDINAMARCA','BOGOTA D.C.':'CUNDINAMARCA',
  'BOGOTÁ D.C.':'CUNDINAMARCA','BOGOTA DISTRITO CAPITAL':'CUNDINAMARCA','D.C.':'CUNDINAMARCA',
  'COTA':'CUNDINAMARCA','FUNZA':'CUNDINAMARCA','MOSQUERA':'CUNDINAMARCA','MADRID':'CUNDINAMARCA',
  'FACATATIVÁ':'CUNDINAMARCA','FACATATIVA':'CUNDINAMARCA','ZIPAQUIRA':'CUNDINAMARCA',
  'ZIPAQUIRÁ':'CUNDINAMARCA','CHIA':'CUNDINAMARCA','CHÍA':'CUNDINAMARCA',
  'CAJICA':'CUNDINAMARCA','CAJICÁ':'CUNDINAMARCA','SOACHA':'CUNDINAMARCA','SIBATÉ':'CUNDINAMARCA',
  'SIBATE':'CUNDINAMARCA','FUSAGASUGA':'CUNDINAMARCA','FUSAGASUGÁ':'CUNDINAMARCA',
  'GIRARDOT':'CUNDINAMARCA','AGUA DE DIOS':'CUNDINAMARCA','TOCAIMA':'CUNDINAMARCA',
  'RICAURTE':'CUNDINAMARCA','VILLETA':'CUNDINAMARCA','NIMAIMA':'CUNDINAMARCA',
  'NOCAIMA':'CUNDINAMARCA','GUADUAS':'CUNDINAMARCA','LA PALMA':'CUNDINAMARCA',
  'PACHO':'CUNDINAMARCA','TOCANCIPA':'CUNDINAMARCA','TOCANCIPÁ':'CUNDINAMARCA',
  'GACHANCIPA':'CUNDINAMARCA','SOPÓ':'CUNDINAMARCA','SOPO':'CUNDINAMARCA',
  'LA CALERA':'CUNDINAMARCA','GUASCA':'CUNDINAMARCA','GUATAVITA':'CUNDINAMARCA',
  'UBATE':'CUNDINAMARCA','UBATÉ':'CUNDINAMARCA','SIMIJACA':'CUNDINAMARCA',
  'SUESCA':'CUNDINAMARCA','NEMOCON':'CUNDINAMARCA','NEMOCÓN':'CUNDINAMARCA',
  'TABIO':'CUNDINAMARCA','TENJO':'CUNDINAMARCA','SUBACHOQUE':'CUNDINAMARCA',
  'EL ROSAL':'CUNDINAMARCA',
  // ATLANTICO
  'BARRANQUILLA':'ATLANTICO','SOLEDAD':'ATLANTICO','MALAMBO':'ATLANTICO',
  'GALAPA':'ATLANTICO','BARANOA':'ATLANTICO','SABANALARGA ATLANTICO':'ATLANTICO',
  'POLONUEVO':'ATLANTICO','PONEDERA':'ATLANTICO','PUERTO COLOMBIA':'ATLANTICO',
  // BOLIVAR
  'CARTAGENA':'BOLIVAR','MAGANGUE':'BOLIVAR','MARIA LA BAJA':'BOLIVAR',
  'EL CARMEN DE BOLIVAR':'BOLIVAR','MOMPOX':'BOLIVAR','TURBACO':'BOLIVAR',
  'ARJONA':'BOLIVAR','SANTA ROSA DEL SUR':'BOLIVAR','SAN PABLO BOLIVAR':'BOLIVAR',
  'MORALES BOLIVAR':'BOLIVAR',
  // MAGDALENA
  'SANTA MARTA':'MAGDALENA','PLATO':'MAGDALENA','FUNDACION':'MAGDALENA',
  'CIENAGA':'MAGDALENA','CIÉNAGA':'MAGDALENA','ARACATACA':'MAGDALENA',
  'EL BANCO':'MAGDALENA','PIVIJAY':'MAGDALENA',
  // SUCRE
  'SINCELEJO':'SUCRE','MAJAGUAL':'SUCRE','SAN MARCOS':'SUCRE','TOLUVIEJO':'SUCRE',
  'COROZAL':'SUCRE','SAMPUES':'SUCRE','MORROA':'SUCRE','OVEJAS':'SUCRE',
  'LOS PALMITOS':'SUCRE','SINCE':'SUCRE','GALERAS':'SUCRE',
  // CORDOBA
  'MONTERIA':'CORDOBA','VALENCIA':'CORDOBA','CERETE':'CORDOBA','CHINU':'CORDOBA',
  'LORICA':'CORDOBA','PUEBLO NUEVO':'CORDOBA','PUERTO LIBERTADOR':'CORDOBA',
  'SAN BERNARDO DEL VIENTO':'CORDOBA','TIERRALTA':'CORDOBA','MONTELIBANO':'CORDOBA',
  'SAHAGUN':'CORDOBA','SAHAGÚN':'CORDOBA','PLANETA RICA':'CORDOBA',
  'COTORRA':'CORDOBA','CANALETE':'CORDOBA','LOS CORDOBAS':'CORDOBA',
  'PUERTO ESCONDIDO':'CORDOBA','SAN ANTERO':'CORDOBA',
  // CESAR
  'VALLEDUPAR':'CESAR','AGUACHICA':'CESAR','LA PAZ':'CESAR','BOSCONIA':'CESAR',
  'CODAZZI':'CESAR','CURUMANI':'CESAR','PAILITAS':'CESAR','CHIMICHAGUA':'CESAR',
  // LA GUAJIRA
  'HATONUEVO':'LA GUAJIRA','RIOHACHA':'LA GUAJIRA','MAICAO':'LA GUAJIRA',
  'MANAURE':'LA GUAJIRA','URIBIA':'LA GUAJIRA','FONSECA':'LA GUAJIRA',
  'SAN JUAN DEL CESAR':'LA GUAJIRA','URUMITA':'LA GUAJIRA','VILLANUEVA LA GUAJIRA':'LA GUAJIRA',
  // RISARALDA
  'PEREIRA':'RISARALDA','DOSQUEBRADAS':'RISARALDA','SANTA ROSA DE CABAL':'RISARALDA',
  'LA VIRGINIA':'RISARALDA','MARSELLA':'RISARALDA','QUINCHIA':'RISARALDA',
  'BELEN DE UMBRIA':'RISARALDA','APÍ A':'RISARALDA','APÍA':'RISARALDA','APIA':'RISARALDA',
  // CALDAS (depto)
  'MANIZALES':'CALDAS','CHINCHINA':'CALDAS','VILLAMARIA':'CALDAS','RIOSUCIO':'CALDAS',
  'SUPIA':'CALDAS','LA DORADA':'CALDAS','VICTORIA':'CALDAS','MANZANARES':'CALDAS',
  'MARQUETALIA':'CALDAS','PENSILVANIA':'CALDAS','PACORA':'CALDAS',
  // QUINDIO
  'ARMENIA':'QUINDIO','CALARCA':'QUINDIO','LA TEBAIDA':'QUINDIO','MONTENEGRO':'QUINDIO',
  'QUIMBAYA':'QUINDIO','CIRCASIA':'QUINDIO','BUENAVISTA':'QUINDIO','SALENTO':'QUINDIO',
  // TOLIMA
  'IBAGUE':'TOLIMA','ESPINAL':'TOLIMA','MELGAR':'TOLIMA','HONDA':'TOLIMA',
  'MARIQUITA':'TOLIMA','FLANDES':'TOLIMA','FRESNO':'TOLIMA','LERIDA':'TOLIMA',
  'AMBALEMA':'TOLIMA','PURIFICACION':'TOLIMA','NATAGAIMA':'TOLIMA','CHAPARRAL':'TOLIMA',
  // HUILA
  'NEIVA':'HUILA','PITALITO':'HUILA','GARZON':'HUILA','GARZÓN':'HUILA',
  'LA PLATA':'HUILA','CAMPOALEGRE':'HUILA','PALERMO':'HUILA','RIVERA':'HUILA',
  'GIGANTE':'HUILA','AGRADO':'HUILA',
  // META
  'VILLAVICENCIO':'META','ACACIAS':'META','GRANADA META':'META','SAN MARTIN META':'META',
  'RESTREPO META':'META','PUERTO GAITAN':'META','CUMARAL':'META',
  // CASANARE
  'YOPAL':'CASANARE','AGUAZUL':'CASANARE','TAURAMENA':'CASANARE','MONTERREY':'CASANARE',
  // ARAUCA
  'ARAUCA':'ARAUCA','SARAVENA':'ARAUCA','TAME':'ARAUCA',
  // NORTE DE SANTANDER
  'CUCUTA':'NORTE DE SANTANDER','CÚCUTA':'NORTE DE SANTANDER',
  'OCAÑA':'NORTE DE SANTANDER','OCANA':'NORTE DE SANTANDER',
  'PAMPLONA':'NORTE DE SANTANDER','VILLA DEL ROSARIO':'NORTE DE SANTANDER',
  'LOS PATIOS':'NORTE DE SANTANDER','EL ZULIA':'NORTE DE SANTANDER',
  // SANTANDER
  'BUCARAMANGA':'SANTANDER','FLORIDABLANCA':'SANTANDER','GIRON':'SANTANDER',
  'GIRÓN':'SANTANDER','PIEDECUESTA':'SANTANDER','LEBRIJA':'SANTANDER',
  'BARRANCABERMEJA':'SANTANDER','SAN GIL':'SANTANDER','SOCORRO':'SANTANDER',
  'VELEZ':'SANTANDER','VELÉZ':'SANTANDER','BARBOSA SANTANDER':'SANTANDER',
  // BOYACA
  'TUNJA':'BOYACA','SOGAMOSO':'BOYACA','DUITAMA':'BOYACA','CHIQUINQUIRA':'BOYACA',
  'PAIPA':'BOYACA','NOBSA':'BOYACA','TIBASOSA':'BOYACA',
  // CAUCA
  'POPAYAN':'CAUCA','POPAYÁN':'CAUCA','SANTANDER DE QUILICHAO':'CAUCA',
  'PUERTO TEJADA':'CAUCA','PADILLA':'CAUCA','MIRANDA CAUCA':'CAUCA',
  // NARIÑO
  'PASTO':'NARIÑO','IPIALES':'NARIÑO','TUMACO':'NARIÑO','TUQUERRES':'NARIÑO',
  'TÚQUERRES':'NARIÑO','LA UNION NARIÑO':'NARIÑO',
  // CHOCO
  'QUIBDO':'CHOCO','QUIBDÓ':'CHOCO','ISTMINA':'CHOCO','CONDOTO':'CHOCO',
  // VICHADA
  'PUERTO CARREÑO':'VICHADA','PUERTO CARRENO':'VICHADA',
  // AMAZONAS
  'LETICIA':'AMAZONAS','PUERTO NARIÑO':'AMAZONAS',
  // PUTUMAYO
  'MOCOA':'PUTUMAYO','PUERTO ASIS':'PUTUMAYO','PUERTO ASÍS':'PUTUMAYO',
  'VILLAGARZON':'PUTUMAYO','VILLAGARZÓN':'PUTUMAYO',
  // CAQUETA
  'FLORENCIA':'CAQUETA','SAN VICENTE DEL CAGUAN':'CAQUETA',
};

// Busca departamento en Nominatim para una ciudad colombiana
const lookupNominatim = async (city: string): Promise<string | null> => {
  try {
    await waitRateLimit();
    const q = encodeURIComponent(`${city}, Colombia`);
    const url = `https://nominatim.openstreetmap.org/search?q=${q}&format=json&addressdetails=1&limit=1&countrycodes=co`;
    const results = await httpsGet(url);
    if (results.length > 0) {
      const addr = results[0].address || {};
      const state = addr.state || addr.region || '';
      if (state) return state.toUpperCase().replace(/\s+/g, ' ').trim();
    }
  } catch { }
  return null;
};

// Normaliza nombre de departamento colombiano desde Nominatim
const normalizeDept = (raw: string): string => {
  const map: Record<string, string> = {
    'ANTIOQUIA': 'ANTIOQUIA', 'CUNDINAMARCA': 'CUNDINAMARCA', 'BOGOTÁ': 'CUNDINAMARCA',
    'BOGOTA': 'CUNDINAMARCA', 'VALLE DEL CAUCA': 'VALLE DEL CAUCA',
    'ATLÁNTICO': 'ATLANTICO', 'ATLANTICO': 'ATLANTICO',
    'BOLÍVAR': 'BOLIVAR', 'BOLIVAR': 'BOLIVAR',
    'CÓRDOBA': 'CORDOBA', 'CORDOBA': 'CORDOBA',
    'SUCRE': 'SUCRE', 'CESAR': 'CESAR', 'MAGDALENA': 'MAGDALENA',
    'LA GUAJIRA': 'LA GUAJIRA', 'RISARALDA': 'RISARALDA',
    'CALDAS': 'CALDAS', 'QUINDÍO': 'QUINDIO', 'QUINDIO': 'QUINDIO',
    'TOLIMA': 'TOLIMA', 'HUILA': 'HUILA', 'META': 'META',
    'CASANARE': 'CASANARE', 'ARAUCA': 'ARAUCA',
    'NORTE DE SANTANDER': 'NORTE DE SANTANDER', 'SANTANDER': 'SANTANDER',
    'BOYACÁ': 'BOYACA', 'BOYACA': 'BOYACA', 'CAUCA': 'CAUCA',
    'NARIÑO': 'NARIÑO', 'CHOCÓ': 'CHOCO', 'CHOCO': 'CHOCO',
    'VICHADA': 'VICHADA', 'AMAZONAS': 'AMAZONAS', 'PUTUMAYO': 'PUTUMAYO',
    'CAQUETÁ': 'CAQUETA', 'CAQUETA': 'CAQUETA', 'GUAVIARE': 'GUAVIARE',
    'VAUPÉS': 'VAUPES', 'GUAINÍA': 'GUAINIA', 'SAN ANDRÉS': 'SAN ANDRES',
  };
  return map[raw] || raw;
};

export const lookupCities = async (req: Request, res: Response) => {
  const { cities } = req.body as { cities: string[] };
  if (!Array.isArray(cities) || cities.length === 0)
    return res.json({ mapping: {} });

  const result: Record<string, string> = {};
  const clean = (s: string) => (s || '').toUpperCase().trim();

  // 1) Consultar todas las ciudades conocidas en DB de una sola vez
  const upperCities = cities.map(clean);
  const { rows: dbRows } = await pool.query(
    `SELECT c.nombre, d.nombre AS departamento
     FROM cfg_ciudades c
     JOIN cfg_departamentos d ON d.id = c.id_departamento
     WHERE UPPER(TRIM(c.nombre)) = ANY($1)`,
    [upperCities]
  );
  for (const row of dbRows) result[clean(row.nombre)] = row.departamento;

  // 2) Para las desconocidas, buscar en BASE_MAP y luego en Nominatim
  const unknown = upperCities.filter(c => !result[c]);
  for (const city of unknown) {
    // Primero checar mapa base
    let dept = BASE_MAP[city] || null;
    let source = 'base_map';

    // Si no está, buscar en Nominatim
    if (!dept) {
      const raw = await lookupNominatim(city);
      if (raw) { dept = normalizeDept(raw); source = 'nominatim'; }
    }

    if (dept) {
      result[city] = dept;
      // Guardar en DB para aprender
      try {
        // Obtener o crear departamento
        let { rows: deptRows } = await pool.query(
          `SELECT id FROM cfg_departamentos WHERE UPPER(TRIM(nombre)) = $1`, [dept]
        );
        let deptId: number;
        if (deptRows.length === 0) {
          const ins = await pool.query(
            `INSERT INTO cfg_departamentos (nombre, estado, usuario_control) VALUES ($1, 'EST-01', 'System') RETURNING id`,
            [dept]
          );
          deptId = ins.rows[0].id;
        } else {
          deptId = deptRows[0].id;
        }
        // Insertar ciudad
        await pool.query(
          `INSERT INTO cfg_ciudades (nombre, id_departamento, estado, usuario_control)
           VALUES ($1, $2, 'EST-01', $3)
           ON CONFLICT DO NOTHING`,
          [city, deptId, source === 'nominatim' ? 'Nominatim' : 'System']
        );
      } catch (e) { /* continuar aunque falle el insert */ }
    }
  }

  res.json({ mapping: result });
};
