FROM atendai/evolution-api:v2.2.3
COPY evolution-entrypoint.sh /usr/local/bin/evolution-entrypoint.sh
RUN chmod +x /usr/local/bin/evolution-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/evolution-entrypoint.sh"]
