services:
  m7app-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    expose:
      - '8080'
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - 'DB_USER=${POSTGRES_USER}'
      - 'DB_PASS=${POSTGRES_PASSWORD}'
      - 'DB_NAME=${POSTGRES_DB}'
      - NODE_ENV=production
      - 'GEMINI_API_KEY=${GEMINI_API_KEY}'
      - 'GOOGLE_API_KEY=${GOOGLE_API_KEY}'
      - 'AI_MODEL=${AI_MODEL}'
      - RCLONE_CONFIG_GDRIVE_TYPE=drive
      - RCLONE_CONFIG_GDRIVE_SCOPE=drive
      - 'RCLONE_CONFIG_GDRIVE_TOKEN={"access_token":"ya29.a0AQvPyIOIpamab25CgGR9UxbuM22-EaKsOP148hP3wgsckvJm5AVXeE1ptPaO9_hUfxYvY1YH1nnGIze97vb4dRAFml7teZgNBuKeMa6GdJG98AEmY3rxQPS3J3jRVBp0_B2ioYbPzOJtlIBZHiqc8ozwF0gv2BWXJB50TdrnROINdGFRYnYxdggEnzSH2VU9-b_MAHUaCgYKAdISARcSFQHGX2MimFgoUmzftA5K3tCXwV3jdg0206","token_type":"Bearer","refresh_token":"1//05NEocypqb9wgCgYIARAAGAUSNwF-L9IrHzvKSUxrxbkccgx-9MegtC6VH084gqRiNcy18hH_pVLLRU0UVu-B8Pcx6eREnIqrL7M","expiry":"2026-04-30T08:37:58.726474705-05:00","expires_in":3599}'
      - RCLONE_CONFIG_GDRIVE_CUMPLIDOS_TYPE=drive
      - RCLONE_CONFIG_GDRIVE_CUMPLIDOS_CLIENT_ID=410862023458-6ca0s3t1ao45ihl4mupodbvugg1gbufo.apps.googleusercontent.com
      - RCLONE_CONFIG_GDRIVE_CUMPLIDOS_CLIENT_SECRET=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
      - RCLONE_CONFIG_GDRIVE_CUMPLIDOS_SCOPE=drive
      - 'RCLONE_CONFIG_GDRIVE_CUMPLIDOS_TOKEN={"access_token":"ya29.a0AQvPyIPpsBRxEE8EnLi79gcuMGRL4A_gK3BHbxuowSsxEt2q6V9-hCnJmGhpx97gfQBT3_1K4WXS-QUoU7MBk09rp_zyfFJ0bsr8IG2mszF0qvXcfeQ0q51QVz0XRcCE3_BjHfr9Ufsbyj1XrYs0kfpMZj9q0bfWsku4Jik0-I__A19hb40NGKWZyZrwwLt4kn7_OwaCgYKAaSARQSFQHGX2MiHLPixjHeqVV88Sm-6WR9RQ0206","token_type":"Bearer","refresh_token":"1//05Eo38IaZetKLCgYIARAAGAUSNwF-L9IRHUPvwi78MEzb9K06mt52ITvS8PR5lZAd_Op9UL8eofrexl7ZMg3j0sqE34sozzxwTsE"}'
    depends_on:
      postgres:
        condition: service_healthy
    mem_limit: 1g
    memswap_limit: 1g

  frontend:
    image: 'ghcr.io/oesantama/m7-frontend:latest'
    pull_policy: always
    restart: always
    expose:
      - '80'
    depends_on:
      m7app-backend:
        condition: service_started
    mem_limit: 128m
    memswap_limit: 128m

  postgres:
    image: 'postgres:15-alpine'
    restart: always
    command: "postgres -c shared_buffers=512MB -c work_mem=8MB -c maintenance_work_mem=128MB -c max_connections=100 -c effective_cache_size=2GB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c synchronous_commit=off -c max_parallel_workers_per_gather=2\n"
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
      interval: 5s
      timeout: 5s
      retries: 5
    mem_limit: 1g
    memswap_limit: 1g

  db-backup:
    image: 'alpine:latest'
    restart: always
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: >
      sh -c "
        apk add --no-cache postgresql-client rclone;
        echo '[M7-BACKUP] Generando rclone.conf para backups...';
        printf '[gdrive]\ntype = drive\nscope = drive\ntoken = {\"access_token\":\"ya29.a0AQvPyIOIpamab25CgGR9UxbuM22-EaKsOP148hP3wgsckvJm5AVXeE1ptPaO9_hUfxYvY1YH1nnGIze97vb4dRAFml7teZgNBuKeMa6GdJG98AEmY3rxQPS3J3jRVBp0_B2ioYbPzOJtlIBZHiqc8ozwF0gv2BWXJB50TdrnROINdGFRYnYxdggEnzSH2VU9-b_MAHUaCgYKAdISARcSFQHGX2MimFgoUmzftA5K3tCXwV3jdg0206\",\"token_type\":\"Bearer\",\"refresh_token\":\"1//05NEocypqb9wgCgYIARAAGAUSNwF-L9IrHzvKSUxrxbkccgx-9MegtC6VH084gqRiNcy18hH_pVLLRU0UVu-B8Pcx6eREnIqrL7M\",\"expiry\":\"2026-04-30T08:37:58.726474705-05:00\",\"expires_in\":3599}\n' > /tmp/rclone.conf;
        while true; do
          DATE=$$(date +%Y-%m-%d_%H-%M-%S);
          echo \"[M7-BACKUP] Iniciando respaldo: $$DATE\";
          PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h $$DB_HOST -U $$POSTGRES_USER $$POSTGRES_DB > /tmp/backup.sql;
          rclone --config /tmp/rclone.conf copy /tmp/backup.sql gdrive:BACKUPS_M7;
          echo \"[M7-BACKUP] Respaldo completado y subido a Drive.\";
          sleep 86400;
        done
      "
    mem_limit: 256m
    memswap_limit: 256m
