# Dockerfile para el Frontend
FROM node:20-alpine AS build

WORKDIR /app

# Instalar dependencias
COPY package*.json ./
ENV NODE_OPTIONS="--max-old-space-size=8192"
RUN npm cache clean --force && npm install

# Build
COPY . .
RUN npm run build

# Etapa de producción
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
