services:
  m7app-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8090:8080"
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
    env_file:
      - .env
    restart: always
    networks:
      - m7-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3010:80"
    depends_on:
      - m7app-backend
    restart: always
    networks:
      - m7-network
    environment:
      - VITE_API_URL=http://m7app-backend:8080/api


  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WAHA_LOG_LEVEL=info
      - WAHA_PRINT_QR=false
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=admin
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.wwebjs_cache:/app/.wwebjs_cache
    networks:
      - m7-network

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=m7_admin
      - POSTGRES_PASSWORD=m7_master_password
      - POSTGRES_DB=m7_logistica
    volumes:
      - m7_logistica_data:/var/lib/postgresql/data
    networks:
      - m7-network

networks:
  m7-network:
    driver: bridge

volumes:
  m7_logistica_data:
