
import { Router } from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import clientRoutes from './client.routes.js';
import articleRoutes from './article.routes.js';
import vehicleRoutes from './vehicle.routes.js';
import driverRoutes from './driver.routes.js';
import documentRoutes from './document.routes.js';
import notificationRoutes from './notification.routes.js';
import whatsappRoutes from './whatsapp.routes.js';
import roleRoutes from './role.routes.js';
import moduleRoutes from './module.routes.js';
import pageRoutes from './page.routes.js';
import permissionRoutes from './permission.routes.js';
import assignmentRoutes from './assignment.routes.js';
import userPermissionRoutes from './user-permission.routes.js';
import aiRoutes from './ai.routes.js';
import twoFactorRoutes from './2fa.routes.js';
import systemRoutes from './system.routes.js';
import masterRoutes from './master.routes.js';
import categoryRoutes from './category.routes.js';
import routeRoutes from './route.routes.js';
import signatureRoutes from './signature.routes.js';
import locationRoutes from './location.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import portalRoutes from './portal.routes.js';
import telemetryRoutes from './telemetry.routes.js';
import adminRoutes from './admin.routes.js';
import estadoRoutes from './estado.routes.js';
import marcaRoutes from './marca.routes.js';
import tipoDocumentoRoutes from './tipo-documento.routes.js';
import unidadMedidaRoutes from './unidad-medida.routes.js';
import notificacionRoutes from './notificacion.routes.js';
import tipoVehiculoRoutes from './tipo-vehiculo.routes.js';
import tipoNotificacionRoutes from './tipo-notificacion.routes.js';
import dispatchRoutes from './dispatch.routes.js';
import pickingRoutes from './picking.routes.js';
import geocodeRoutes from './geocode.routes.js';
import backupRoutes from './backup.routes.js';
import trainingRoutes from './training.routes.js';
import inventoryNewsRoutes from './inventory-news.routes.js';
import grupoInterRoutes from './grupoInter.routes.js';
import conciliationRoutes from './conciliation.routes.js';
import inventoryRoutes from './inventory.routes.js';
import ghMiscelaneosRoutes from './gh-miscelaneos.routes.js';
import ghPersonalRoutes from './gh-personal.routes.js';
import cfgCiudadesRoutes from './cfg-ciudades.routes.js';
import ghVisitasRoutes from './gh-visitas.routes.js';
import deliveryScheduleRoutes from './delivery-schedule.routes.js';
import ajoverB36Routes from './ajover-b36.routes.js';
import managementReportRoutes from './management-report.routes.js';
import provClienteRoutes from './prov-cliente.routes.js';

import ghMasterInventarioRoutes from './gh-master-inventario.routes.js';
import ghEntradasSalidasRoutes from './gh-entradas-salidas.routes.js';

const router = Router();

// ... existing routes ...
router.use('/masters', masterRoutes);
router.use('/categories', categoryRoutes);
router.use('/training', trainingRoutes);
router.use('/inventory-news', inventoryNewsRoutes);
router.use('/routes', routeRoutes);
router.use('/admin', adminRoutes); // Database Manager
router.use('/estados', estadoRoutes);
router.use('/marcas', marcaRoutes);
router.use('/tipos-documento', tipoDocumentoRoutes);
router.use('/unidades-medida', unidadMedidaRoutes);
router.use('/notificaciones-config', notificacionRoutes);
router.use('/tipos-vehiculo', tipoVehiculoRoutes);
router.use('/tipos-notificacion', tipoNotificacionRoutes);
router.use('/auth', authRoutes);
router.use('/2fa', twoFactorRoutes);
router.use('/users', userRoutes);
router.use('/clients', clientRoutes);
router.use('/articles', articleRoutes);
router.use('/vehicles', vehicleRoutes);
router.use('/documents', documentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/roles', roleRoutes);
router.use('/modules', moduleRoutes);
router.use('/pages', pageRoutes);
router.use('/permissions', permissionRoutes);
router.use('/drivers', driverRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/user-permissions', userPermissionRoutes);
router.use('/ai', aiRoutes);
router.use('/system', systemRoutes);
router.use('/signatures', signatureRoutes);
router.use('/locations', locationRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/portal', portalRoutes);
router.use('/telemetry', telemetryRoutes);
router.use('/dispatch', dispatchRoutes);
router.use('/picking', pickingRoutes);
router.use('/geocode', geocodeRoutes);
router.use('/admin/backup', backupRoutes); // DB Backup endpoint
router.use('/grupo-inter', grupoInterRoutes);
router.use('/conciliation', conciliationRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/gh-miscelaneos', ghMiscelaneosRoutes);
router.use('/gh-personal', ghPersonalRoutes);
router.use('/cfg-ciudades', cfgCiudadesRoutes);
router.use('/gh-visitas', ghVisitasRoutes);
router.use('/delivery-schedules', deliveryScheduleRoutes);
router.use('/ajover-b36', ajoverB36Routes);
router.use('/management-reports', managementReportRoutes);
router.use('/prov-clientes', provClienteRoutes);
router.use('/gh-master-inventario', ghMasterInventarioRoutes);
router.use('/gh-entradas-salidas', ghEntradasSalidasRoutes);

export default router;

