import { test, expect } from '@playwright/test';

const BASE_URL = 'http://localhost:3000';

const MASTERS_TO_TEST = [
  { name: 'APROBAR FIRMA', buttonText: 'APROBAR FIRMA' }, // Ajustar el caso según el ID / placeholder
  { name: 'ARTICULOS', buttonText: 'NUEVO ARTICULO' },
  { name: 'CLIENTES', buttonText: 'NUEVO CLIENTE' },
  { name: 'ESTADOS GLOBALES', buttonText: 'NUEVO ESTADO' },
  { name: 'FIRMAS DIGITALES', buttonText: 'REGISTRAR FIRMA' },
  { name: 'MARCAS', buttonText: 'NUEVA MARCA' },
  { name: 'NOTIFICACIONES', buttonText: 'NUEVA NOTIFICACIÓN' },
  { name: 'TIPOS DE DOCUMENTO', buttonText: 'NUEVO TIPO DOCUMENTO' },
  { name: 'TIPOS DE VEHÍCULO', buttonText: 'NUEVO TIPO VEHICULO' },
  { name: 'UNIDADES DE MEDIDA', buttonText: 'NUEVA UNIDAD MEDIDA' },
];

test.describe('CRUD Exhaustivo de Maestros', () => {

  test.beforeEach(async ({ page }) => {
    // Iniciar Sesión como Admin
    await page.goto(BASE_URL);
    
    const emailInput = page.locator('input[type="text"]');
    await emailInput.fill('1121837405'); // Admin
    
    const passInput = page.locator('input[type="password"]');
    await passInput.fill('admin123'); // Password
    
    const loginButton = page.locator('button[type="submit"]');
    await loginButton.click();

    await page.waitForTimeout(2000); // Esperar que carguen módulos
  });

  for (const master of MASTERS_TO_TEST) {
    test(`Test CRUD de Master: ${master.name}`, async ({ page }) => {
      // 1. Navegar a Configuración Maestros
      const masterMenuBtn = page.locator('button').filter({ hasText: /CONFIGURACI.N MAESTROS/i }).first();
      await expect(masterMenuBtn).toBeVisible({ timeout: 10000 });
      await masterMenuBtn.click();
      await page.waitForTimeout(1000); // Wait for transition accordion

      // 2. Hacer click en el submenu
      const submenuBtn = page.locator('button').filter({ hasText: new RegExp(master.name, 'i') }).first();
      await submenuBtn.click();
      
      await page.waitForTimeout(1000);
      
      // Validar que se muestre en pantalla
      const title = page.locator('h1', { hasText: new RegExp(master.name, 'i') }).first();
      await expect(title).toBeVisible({ timeout: 10000 });
      
      console.log(`[OK] Entrando a ${master.name}`);

      // Casos Especiales (Como Firma donde el Botón es diferente o Ausente)
      if (master.name === 'APROBAR FIRMA') {
         // Validar que exista al menos la cabecera o info
         const table = page.locator('table').first();
         await expect(table).toBeVisible({ timeout: 5000 }).catch(() => console.log('Sin tabla visible en firma'));
         return; 
      }
      
      if (master.name === 'FIRMAS DIGITALES') {
         const table = page.locator('table').first();
         await expect(table).toBeVisible({ timeout: 5000 }).catch(() => console.log('Sin tabla visible en firma'));
         return; 
      }

      // 3. Crear Registro
      // Busca botón exacto para abrir modal (evitar clics erróneos en móviles)
      const btnNuevo = page.getByRole('button', { name: new RegExp(master.buttonText, 'i') }).first();
      await expect(btnNuevo).toBeVisible({timeout: 5000});
      await btnNuevo.click();
      await page.waitForTimeout(500);

      const modalInput = page.locator('.fixed input').first();
      await modalInput.fill('TEST-AUTOGENERATED-001');

      try {
         // Si hay un description extra
         const modalDesc = page.locator('.fixed input').nth(1);
         await modalDesc.fill('Desc Automatic');
      } catch (e) {}
      
      // Guardar
      const saveBtn = page.getByRole('button', { name: /GUARDAR/i }).first();
      await saveBtn.click();
      
      console.log(`[OK] Creado temporal en ${master.name}`);
      await page.waitForTimeout(1500);

      // 4. Edición / Borrado (Cleanup Simple)
      // Buscamos la fila "TEST-AUTOGENERATED-001" en la tabla
      const deleteIcon = page.locator('tr').filter({ hasText: 'TEST-AUTOGENERATED-001' }).locator('button').last(); // Suponiendo que borrar está al final
      await deleteIcon.click();
      console.log(`[OK] Eliminado temporal en ${master.name}`);
      await page.waitForTimeout(1000);
      
      // Confirmar Borrado si hubiera confirmación extra (SweetAlert)
      const confirmDelete = page.getByRole('button', { name: /SI, ELIMINAR/i }).first();
      if (await confirmDelete.isVisible()) {
          await confirmDelete.click();
      }
    });
  }
});
